### PR TITLE
added option to decide whether an put should overwrite an existing file

### PR DESCRIPTION
**Pull request by balu-**
not browserify but hopefuly usefull 😉

### CODE REVIEW

**Comment by perry-mitchell** [comment]
Seems that the tests are failing.

Also, I think it would be nicer to support an options object, rather than a new parameter. For instance:

    options = {
        overwrite: true
    }

**Comment by balu-** [comment]
options like this? 

I ran the tests, but could not find anything failing.
Could you point me in the direction of the failing test?

(sorry for any beginner mistake, i'm new to npm/node/js)


----
 find ./test/specs -name '*.spec.js' | xargs mocha -R spec



  adapter:alter
    deleteItem
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ deletes files (41ms)
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ deletes directories
    moveItem
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ moves the file

  adapter:get
    getDirectoryContents
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ gets all objects in directory (39ms)
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ gets objects in correct form
    getFileContents
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ gets contents of a remote file
    getStat
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ stats files
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ stats directories
    getTextContents
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ gets contents of a remote file

  adapter:put
    createDirectory
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ creates the specified directory
    putFileContents
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ puts the file correctly in the remote directory
    putTextContents
[info] jsDAV server running on http://127.0.0.1:9999
      ✓ puts the text file correctly in the remote directory


  12 passing (5s)

**Comment by perry-mitchell** [comment]
Seems that you fixed it on the next commit:
image
image

**Comment by perry-mitchell** [comment]
Thanks @balu- - There's a couple of things I'll tweak in the way of docs and defaults, but your changes look good.

**Pull request merged**
