### PR TITLE
feat(getDirectoryContents): allow returning current directory

### LINKED ISSUE #178: Return current directory info on getDirectoryContents
Hello!
Thanks for your awesome lib :)

I would like to not filter out the current directory while doing a `getDirectoryContents` to avoid an extra request to store the data, is this possible? !

https://github.com/perry-mitchell/webdav-client/blob/94f70538d1f47dce8f450efb647c9006d9a72bec/source/interface/directoryContents.js#L42-L47

Have a great day!

### PR DESCRIPTION
**Pull request by skjnldsv**
fix #178 

Allows you to get the directory within its contents results.

- [x] Feature
- [x] Testing
- [x] Formatting

### CODE REVIEW

**Comment by skjnldsv** [comment]
```
[0] Chrome Headless 109.0.5414.74 (Linux x86_64): Executed 27 of 27 SUCCESS (0.361 secs / 0.315 secs)
[0] 20 01 2023 15:53:30.611:WARN [launcher]: Firefox has not captured in 60000 ms, killing.
[0] 20 01 2023 15:53:30.619:INFO [launcher]: Trying to start Firefox again (1/2).
[0] 20 01 2023 15:54:30.623:WARN [launcher]: Firefox has not captured in 60000 ms, killing.
[0] 20 01 2023 15:54:30.632:INFO [launcher]: Trying to start Firefox again (2/2).
[0] 20 01 2023 15:55:30.636:WARN [launcher]: Firefox has not captured in 60000 ms, killing.
[0] 20 01 2023 15:55:30.644:ERROR [launcher]: Firefox failed 2 times (timeout). Giving up.
[0] 
[0] Chrome Headless 109.0.5414.74 (Linux x86_64): Executed 27 of 27 SUCCESS (0.361 secs / 0.315 secs)
[0] TOTAL: 27 SUCCESS
```

I think the failure is unrelated
also happened in [recent master merge](https://github.com/perry-mitchell/webdav-client/actions/runs/3922809852/jobs/6705997356)

**Review by perry-mitchell — APPROVED** [review]
Awesome!

**Comment by perry-mitchell** [comment]
> think the failure is unrelated
Yep, looks so. I'll merge anyway.

Thanks for this!

**Comment by perry-mitchell** [comment]
Released in `5.0.0-r2`

**Comment by skjnldsv** [comment]
Thank you @perry-mitchell :hugs:

**Comment by philipp-serfling** [comment]
@perry-mitchell I think you made a tiny mistake because this `filter` does not seem to work, and so it always includes the current directory
https://github.com/perry-mitchell/webdav-client/pull/334/files#diff-e430db3c0f15a5ba77e989cedab8a7e1ff74162c1cd0061b55072dcadbda7e9dR88

**Comment by skjnldsv** [comment]
@philipp-serfling works fine for us :shrug:

**Comment by philipp-serfling** [comment]
@skjnldsv I thought you were particularily interested that the current directory **IS** included?
For me it does not work to exclude it.

**Comment by skjnldsv** [comment]
@philipp-serfling it's excluded by default.
 you have to provide `includeSelf: true` for it to be returned alongside its contents

**Comment by perry-mitchell** [comment]
@philipp-serfling This is all tested to work, here: https://github.com/perry-mitchell/webdav-client/blob/c446c664e0da8a6049b44f35f190477fd09c9f16/test/node/operations/getDirectoryContents.spec.ts#L297

If you find a bug it'd be helpful to make a PR with a test to show it failing, and then create an issue.

Locking this PR discussion.

**Pull request merged**
