### PR TITLE
Added getFileDownloadLink function

### PR DESCRIPTION
**Pull request by yoeven**
It returns a remote URL with an authentication query that can be directly accessed as a download link, for example in `<a href="">` or `window.location` to prompt a save dialog. Works similarly to `getFileContents`.

### CODE REVIEW

**Comment by yoeven** [comment]
I know Owncloud/Nextcloud WebDAV service will work (tested) and it should work on the other WebDAV services that you've stated in your `README.md` as it follows the same options and calls. The only issue is that it exposes the username & password in the URL, so links can't be shared with others or have to be encrypted somehow.

**Comment by perry-mitchell** [comment]
Ah cool.. Well nice that it seems to be a more common feature. You're right that the URL authentication method is not ideal, but that choice can be up to the users (with fair warning of course). I'll review this a bit later, and then will most likely add something in the readme about it.

It's cool that this would allow the request to be handled externally using the URL - I'd see this as almost the best use case for this method.

**Comment by perry-mitchell** [comment]
@yoeven could you please add a unit test for this new method?

**Comment by yoeven** [comment]
Sorry @perry-mitchell, I've never worked with unit testing before but will look into it

**Comment by perry-mitchell** [comment]
Thanks for this @yoeven - No unit test necessary for this PR, I'll write one myself now. Cheers!

**Pull request merged**
